name: "infrastructure sync"

# on:
#   push:
#     branches:
#       - master

on:
  push:
    branches:
      - my-gf

jobs:
  steve-jobs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.8.5
      - run: ls
      - run: |
          cd src
          tofu fmt
          tofu init
          # tofu plan -var "aws-access-key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "aws-secret-key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          tofu plan
        env:
          TF_VAR_aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
